package com.tfgllopis.integracion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Cabecera_administrador_Ventana extends HorizontalLayout {
	protected Label usernameL;
	protected Button perfilB;
	protected Button listarUsuariosB;
	protected Button crearUsuarioB;
	protected Button desconectarB;

	public Cabecera_administrador_Ventana() {
		Design.read(this);
	}
}
