package com.tfgllopis.integracion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Crear_usuario_Ventana extends VerticalLayout {
	protected TextField usuarioF;
	protected TextField emailF;
	protected PasswordField passwordF;
	protected PasswordField password2F;
	protected CheckBox activoChckBx;
	protected VerticalLayout layoutRoles;
	protected RadioButtonGroup<java.lang.String> rolesRadio;
	protected Button guardarB;
	protected Button cancelarB;
	protected Label correctoL;
	protected Label errorL;

	public Crear_usuario_Ventana() {
		Design.read(this);
	}
}
