package com.tfgllopis.integracion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Editar_pirata_Ventana extends VerticalLayout {
	protected Label tituloL;
	protected HorizontalLayout layoutInstalaciones;
	protected GridLayout layoutNaves;
	protected Button guardarB;
	protected Button cancelarB;
	protected Label errorL;
	protected Label correctoL;

	public Editar_pirata_Ventana() {
		Design.read(this);
	}
}
