package com.tfgllopis.integracion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Editar_nave_Ventana extends VerticalLayout {
	protected Image imagenNave;
	protected Upload subirImagen;
	protected TextField nombreF;
	protected ComboBox<com.tfgllopis.integracion.TipoNave> tipoNaveCombo;
	protected Button caracteristicasB;
	protected Panel panelCaracteristicas;
	protected TextField saludF;
	protected TextField escudoF;
	protected TextField ataqueF;
	protected TextField agilidadF;
	protected TextField velocidadF;
	protected TextField cargaF;
	protected Button costeB;
	protected Panel panelCoste;
	protected TextField metalF;
	protected TextField oroF;
	protected TextField petroleoF;
	protected CheckBox bloqueadaChckBx;
	protected Panel panelPiratas;
	protected VerticalLayout layoutDesbloqueo;
	protected Label correctoL;
	protected Label errorL;
	protected Button guardarB;
	protected Button cancelarB;

	public Editar_nave_Ventana() {
		Design.read(this);
	}
}
