package com.tfgllopis.integracion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Hangar_Ventana extends HorizontalLayout {
	protected VerticalLayout tipoNaveLayout;
	protected VerticalLayout construirLayout;
	protected Label nombreTipoL;
	protected Image flechaIzq;
	protected VerticalLayout naveLayout;
	protected Image flechaDer;
	protected TextField construirF;
	protected Button construirB;
	protected VerticalLayout cancelarConstruccionLayout;
	protected Label saludL;
	protected Label ataqueL;
	protected Label cargaL;
	protected Label escudoL;
	protected Label agilidadL;
	protected Label velocidadL;
	protected Label metalL;
	protected Label petroleoL;
	protected Label oroL;
	protected Label correctoL;
	protected Label errorL;

	public Hangar_Ventana() {
		Design.read(this);
	}
}
