package com.tfgllopis.integracion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Iniciar_sesion_Ventana extends VerticalLayout {
	protected Label tituloL;
	protected Image imagenLogo;
	protected TextField usuarioF;
	protected PasswordField passwordF;
	protected Button loginB;
	protected Label errorL;
	protected Label correctoL;
	protected Button registrarseB;

	public Iniciar_sesion_Ventana() {
		Design.read(this);
	}
}
