package com.tfgllopis.integracion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Instalacion_jugador_Ventana extends VerticalLayout {
	protected Label produccionL;
	protected Label nivelL;
	protected Label metalL;
	protected Label oroL;
	protected Label petroleoL;
	protected Button subirNivelB;

	public Instalacion_jugador_Ventana() {
		Design.read(this);
	}
}
