package com.tfgllopis.integracion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensaje_batalla_Ventana extends VerticalLayout {
	protected Label tipoL;
	protected TextField asuntoF;
	protected TabSheet nombreNaveL;
	protected VerticalLayout atacantesLayout;
	protected VerticalLayout defensoresLayout;
	protected HorizontalLayout recursosLayout;
	protected HorizontalLayout navesDesbloqueadasLayout;
	protected Button borrarB;

	public Mensaje_batalla_Ventana() {
		Design.read(this);
	}
}
