package com.tfgllopis.integracion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Pagina_principal_Ventana extends VerticalLayout {
	protected Image imagenMetal;
	protected Label metalL;
	protected Image imagenOro;
	protected Label oroL;
	protected Image imagenPetroleo;
	protected Label petroleoL;

	public Pagina_principal_Ventana() {
		Design.read(this);
	}
}
